# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/veily/桌面/LiGan/Pose6dSolver-pyqt/ui_files/DockGraphWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(682, 440)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.dockGraphWidget = QtWidgets.QDockWidget(Form)
        self.dockGraphWidget.setAcceptDrops(False)
        self.dockGraphWidget.setFloating(False)
        self.dockGraphWidget.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable|QtWidgets.QDockWidget.DockWidgetMovable)
        self.dockGraphWidget.setObjectName("dockGraphWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setEnabled(True)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.layout_main = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.layout_main.setObjectName("layout_main")
        self.groupbox_visualize = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupbox_visualize.setAutoFillBackground(False)
        self.groupbox_visualize.setObjectName("groupbox_visualize")
        self.layout_visualize = QtWidgets.QVBoxLayout(self.groupbox_visualize)
        self.layout_visualize.setObjectName("layout_visualize")
        self.graphics_view = QtWidgets.QGraphicsView(self.groupbox_visualize)
        self.graphics_view.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.graphics_view.setMouseTracking(True)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphics_view.setBackgroundBrush(brush)
        self.graphics_view.setObjectName("graphics_view")
        self.layout_visualize.addWidget(self.graphics_view)
        self.layout_coord_bar = QtWidgets.QHBoxLayout()
        self.layout_coord_bar.setObjectName("layout_coord_bar")
        self.label1 = QtWidgets.QLabel(self.groupbox_visualize)
        self.label1.setObjectName("label1")
        self.layout_coord_bar.addWidget(self.label1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.layout_coord_bar.addItem(spacerItem)
        self.label2 = QtWidgets.QLabel(self.groupbox_visualize)
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.layout_coord_bar.addWidget(self.label2)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.layout_coord_bar.addItem(spacerItem1)
        self.label3 = QtWidgets.QLabel(self.groupbox_visualize)
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.layout_coord_bar.addWidget(self.label3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_coord_bar.addItem(spacerItem2)
        self.pushbtn_show_table = QtWidgets.QPushButton(self.groupbox_visualize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushbtn_show_table.sizePolicy().hasHeightForWidth())
        self.pushbtn_show_table.setSizePolicy(sizePolicy)
        self.pushbtn_show_table.setMinimumSize(QtCore.QSize(80, 0))
        self.pushbtn_show_table.setMaximumSize(QtCore.QSize(10, 24))
        self.pushbtn_show_table.setAutoFillBackground(False)
        self.pushbtn_show_table.setCheckable(True)
        self.pushbtn_show_table.setChecked(False)
        self.pushbtn_show_table.setAutoRepeat(False)
        self.pushbtn_show_table.setAutoDefault(True)
        self.pushbtn_show_table.setDefault(True)
        self.pushbtn_show_table.setFlat(False)
        self.pushbtn_show_table.setObjectName("pushbtn_show_table")
        self.layout_coord_bar.addWidget(self.pushbtn_show_table)
        self.layout_visualize.addLayout(self.layout_coord_bar)
        self.layout_main.addWidget(self.groupbox_visualize)
        self.groupbox_points = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupbox_points.setObjectName("groupbox_points")
        self.layout_points = QtWidgets.QVBoxLayout(self.groupbox_points)
        self.layout_points.setObjectName("layout_points")
        self.groupbox_show_points = QtWidgets.QGroupBox(self.groupbox_points)
        self.groupbox_show_points.setObjectName("groupbox_show_points")
        self.layout_show_points = QtWidgets.QHBoxLayout(self.groupbox_show_points)
        self.layout_show_points.setObjectName("layout_show_points")
        self.table_widget_show_points = QtWidgets.QTableWidget(self.groupbox_show_points)
        self.table_widget_show_points.setObjectName("table_widget_show_points")
        self.table_widget_show_points.setColumnCount(0)
        self.table_widget_show_points.setRowCount(0)
        self.layout_show_points.addWidget(self.table_widget_show_points)
        self.layout_points.addWidget(self.groupbox_show_points)
        self.groupbox_choose_points = QtWidgets.QGroupBox(self.groupbox_points)
        self.groupbox_choose_points.setFlat(False)
        self.groupbox_choose_points.setCheckable(False)
        self.groupbox_choose_points.setObjectName("groupbox_choose_points")
        self.layout_choose_points = QtWidgets.QHBoxLayout(self.groupbox_choose_points)
        self.layout_choose_points.setObjectName("layout_choose_points")
        self.tab_widget_objs = QtWidgets.QTabWidget(self.groupbox_choose_points)
        self.tab_widget_objs.setObjectName("tab_widget_objs")
        self.layout_choose_points.addWidget(self.tab_widget_objs)
        self.layout_points.addWidget(self.groupbox_choose_points)
        self.layout_main.addWidget(self.groupbox_points)
        self.dockGraphWidget.setWidget(self.dockWidgetContents)
        self.gridLayout.addWidget(self.dockGraphWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tab_widget_objs.setCurrentIndex(-1)
        self.pushbtn_show_table.toggled['bool'].connect(self.groupbox_points.setHidden)
        self.pushbtn_show_table.toggled['bool'].connect(self.groupbox_points.update)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupbox_visualize.setTitle(_translate("Form", "GroupBox"))
        self.label1.setText(_translate("Form", "像素坐标(u, v):"))
        self.pushbtn_show_table.setText(_translate("Form", "隐藏表格"))
        self.groupbox_points.setTitle(_translate("Form", "点对:"))
        self.groupbox_show_points.setTitle(_translate("Form", "显示:"))
        self.groupbox_choose_points.setTitle(_translate("Form", "选择:"))

