# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Li\Desktop\Pose6dSolver-pyqt\ui_files\SettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(481, 782)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rbtn_dlt = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbtn_dlt.setChecked(True)
        self.rbtn_dlt.setObjectName("rbtn_dlt")
        self.verticalLayout_2.addWidget(self.rbtn_dlt)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.rbtn_manual = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn_manual.setChecked(True)
        self.rbtn_manual.setObjectName("rbtn_manual")
        self.gridLayout.addWidget(self.rbtn_manual, 0, 0, 1, 1)
        self.rbtn_epnp = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn_epnp.setObjectName("rbtn_epnp")
        self.gridLayout.addWidget(self.rbtn_epnp, 2, 0, 1, 1)
        self.rbtn_pso = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn_pso.setObjectName("rbtn_pso")
        self.gridLayout.addWidget(self.rbtn_pso, 0, 1, 1, 1)
        self.rbtn_none = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn_none.setObjectName("rbtn_none")
        self.gridLayout.addWidget(self.rbtn_none, 2, 1, 1, 1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rbtn_ellipse = QtWidgets.QRadioButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbtn_ellipse.sizePolicy().hasHeightForWidth())
        self.rbtn_ellipse.setSizePolicy(sizePolicy)
        self.rbtn_ellipse.setObjectName("rbtn_ellipse")
        self.horizontalLayout_2.addWidget(self.rbtn_ellipse)
        self.rbtn_correspond = QtWidgets.QRadioButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbtn_correspond.sizePolicy().hasHeightForWidth())
        self.rbtn_correspond.setSizePolicy(sizePolicy)
        self.rbtn_correspond.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.rbtn_correspond.setCheckable(True)
        self.rbtn_correspond.setChecked(True)
        self.rbtn_correspond.setAutoExclusive(True)
        self.rbtn_correspond.setObjectName("rbtn_correspond")
        self.horizontalLayout_2.addWidget(self.rbtn_correspond)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupbox_hperparams_adam = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupbox_hperparams_adam.setCheckable(True)
        self.groupbox_hperparams_adam.setObjectName("groupbox_hperparams_adam")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupbox_hperparams_adam)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinbox_alpha_adam = QtWidgets.QDoubleSpinBox(self.groupbox_hperparams_adam)
        self.spinbox_alpha_adam.setObjectName("spinbox_alpha_adam")
        self.gridLayout_2.addWidget(self.spinbox_alpha_adam, 1, 1, 1, 1)
        self.spinbox_beta2_adam = QtWidgets.QDoubleSpinBox(self.groupbox_hperparams_adam)
        self.spinbox_beta2_adam.setObjectName("spinbox_beta2_adam")
        self.gridLayout_2.addWidget(self.spinbox_beta2_adam, 3, 1, 1, 1)
        self.spinbox_beta1_adam = QtWidgets.QDoubleSpinBox(self.groupbox_hperparams_adam)
        self.spinbox_beta1_adam.setObjectName("spinbox_beta1_adam")
        self.gridLayout_2.addWidget(self.spinbox_beta1_adam, 2, 1, 1, 1)
        self.label_niters_adam = QtWidgets.QLabel(self.groupbox_hperparams_adam)
        self.label_niters_adam.setObjectName("label_niters_adam")
        self.gridLayout_2.addWidget(self.label_niters_adam, 0, 0, 1, 1)
        self.label_alpha_adam = QtWidgets.QLabel(self.groupbox_hperparams_adam)
        self.label_alpha_adam.setObjectName("label_alpha_adam")
        self.gridLayout_2.addWidget(self.label_alpha_adam, 1, 0, 1, 1)
        self.label_beta1_adam = QtWidgets.QLabel(self.groupbox_hperparams_adam)
        self.label_beta1_adam.setObjectName("label_beta1_adam")
        self.gridLayout_2.addWidget(self.label_beta1_adam, 2, 0, 1, 1)
        self.label_beta2_adam = QtWidgets.QLabel(self.groupbox_hperparams_adam)
        self.label_beta2_adam.setObjectName("label_beta2_adam")
        self.gridLayout_2.addWidget(self.label_beta2_adam, 3, 0, 1, 1)
        self.spinbox_niters_adam = QtWidgets.QSpinBox(self.groupbox_hperparams_adam)
        self.spinbox_niters_adam.setObjectName("spinbox_niters_adam")
        self.gridLayout_2.addWidget(self.spinbox_niters_adam, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupbox_hperparams_adam)
        self.groupbox_hperparams_lm = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupbox_hperparams_lm.setCheckable(True)
        self.groupbox_hperparams_lm.setChecked(False)
        self.groupbox_hperparams_lm.setObjectName("groupbox_hperparams_lm")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupbox_hperparams_lm)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.groupbox_hperparams_lm)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_3.addWidget(self.doubleSpinBox_5, 2, 1, 1, 1)
        self.spinbox_alpha_lm = QtWidgets.QDoubleSpinBox(self.groupbox_hperparams_lm)
        self.spinbox_alpha_lm.setObjectName("spinbox_alpha_lm")
        self.gridLayout_3.addWidget(self.spinbox_alpha_lm, 1, 1, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.groupbox_hperparams_lm)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_3.addWidget(self.doubleSpinBox_6, 3, 1, 1, 1)
        self.label_niters_lm = QtWidgets.QLabel(self.groupbox_hperparams_lm)
        self.label_niters_lm.setObjectName("label_niters_lm")
        self.gridLayout_3.addWidget(self.label_niters_lm, 0, 0, 1, 1)
        self.label_alpha_lm = QtWidgets.QLabel(self.groupbox_hperparams_lm)
        self.label_alpha_lm.setObjectName("label_alpha_lm")
        self.gridLayout_3.addWidget(self.label_alpha_lm, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupbox_hperparams_lm)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupbox_hperparams_lm)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.spinbox_niters_lm = QtWidgets.QSpinBox(self.groupbox_hperparams_lm)
        self.spinbox_niters_lm.setObjectName("spinbox_niters_lm")
        self.gridLayout_3.addWidget(self.spinbox_niters_lm, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupbox_hperparams_lm)
        self.groupbox_hperparams_pso = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupbox_hperparams_pso.setCheckable(True)
        self.groupbox_hperparams_pso.setChecked(False)
        self.groupbox_hperparams_pso.setObjectName("groupbox_hperparams_pso")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupbox_hperparams_pso)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_c1_pso = QtWidgets.QLabel(self.groupbox_hperparams_pso)
        self.label_c1_pso.setObjectName("label_c1_pso")
        self.gridLayout_4.addWidget(self.label_c1_pso, 3, 0, 1, 1)
        self.spinbox_npops_pso = QtWidgets.QDoubleSpinBox(self.groupbox_hperparams_pso)
        self.spinbox_npops_pso.setObjectName("spinbox_npops_pso")
        self.gridLayout_4.addWidget(self.spinbox_npops_pso, 1, 1, 1, 1)
        self.label_niters_pso = QtWidgets.QLabel(self.groupbox_hperparams_pso)
        self.label_niters_pso.setObjectName("label_niters_pso")
        self.gridLayout_4.addWidget(self.label_niters_pso, 0, 0, 1, 1)
        self.label_npops_pso = QtWidgets.QLabel(self.groupbox_hperparams_pso)
        self.label_npops_pso.setObjectName("label_npops_pso")
        self.gridLayout_4.addWidget(self.label_npops_pso, 1, 0, 1, 1)
        self.label_w_pso = QtWidgets.QLabel(self.groupbox_hperparams_pso)
        self.label_w_pso.setObjectName("label_w_pso")
        self.gridLayout_4.addWidget(self.label_w_pso, 2, 0, 1, 1)
        self.label_c2_pso = QtWidgets.QLabel(self.groupbox_hperparams_pso)
        self.label_c2_pso.setObjectName("label_c2_pso")
        self.gridLayout_4.addWidget(self.label_c2_pso, 4, 0, 1, 1)
        self.spinbox_w_pso = QtWidgets.QDoubleSpinBox(self.groupbox_hperparams_pso)
        self.spinbox_w_pso.setObjectName("spinbox_w_pso")
        self.gridLayout_4.addWidget(self.spinbox_w_pso, 2, 1, 1, 1)
        self.spinbox_c1_pso = QtWidgets.QDoubleSpinBox(self.groupbox_hperparams_pso)
        self.spinbox_c1_pso.setObjectName("spinbox_c1_pso")
        self.gridLayout_4.addWidget(self.spinbox_c1_pso, 3, 1, 1, 1)
        self.spinbox_c2_pso = QtWidgets.QDoubleSpinBox(self.groupbox_hperparams_pso)
        self.spinbox_c2_pso.setObjectName("spinbox_c2_pso")
        self.gridLayout_4.addWidget(self.spinbox_c2_pso, 4, 1, 1, 1)
        self.spinbox_niters_pso = QtWidgets.QSpinBox(self.groupbox_hperparams_pso)
        self.spinbox_niters_pso.setObjectName("spinbox_niters_pso")
        self.gridLayout_4.addWidget(self.spinbox_niters_pso, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupbox_hperparams_pso)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.groupBox_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        self.groupBox_8 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbtn_adam = QtWidgets.QRadioButton(self.groupBox_8)
        self.rbtn_adam.setChecked(True)
        self.rbtn_adam.setObjectName("rbtn_adam")
        self.horizontalLayout.addWidget(self.rbtn_adam)
        self.rbtn_lm = QtWidgets.QRadioButton(self.groupBox_8)
        self.rbtn_lm.setObjectName("rbtn_lm")
        self.horizontalLayout.addWidget(self.rbtn_lm)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.groupBox_8)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.rbtn_adam.toggled['bool'].connect(self.groupbox_hperparams_adam.setChecked)
        self.rbtn_pso.toggled['bool'].connect(self.groupbox_hperparams_pso.setChecked)
        self.rbtn_lm.toggled['bool'].connect(self.groupbox_hperparams_lm.setChecked)
        self.groupbox_hperparams_adam.clicked['bool'].connect(self.rbtn_adam.click)
        self.groupbox_hperparams_lm.clicked['bool'].connect(self.rbtn_lm.setChecked)
        self.groupbox_hperparams_pso.clicked['bool'].connect(self.rbtn_pso.setChecked)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "设置"))
        self.groupBox_2.setTitle(_translate("Dialog", "标定方法:"))
        self.rbtn_dlt.setText(_translate("Dialog", "DLT"))
        self.groupBox.setTitle(_translate("Dialog", "初始化方法:"))
        self.rbtn_manual.setText(_translate("Dialog", "手工调整"))
        self.rbtn_epnp.setText(_translate("Dialog", "EPnP约束(需要2D与3D关键点一致对应,且N>=4)"))
        self.rbtn_pso.setText(_translate("Dialog", "PSO (粒子群算法)"))
        self.rbtn_none.setText(_translate("Dialog", "不初始化"))
        self.groupBox_3.setTitle(_translate("Dialog", "物体1-选点方式:"))
        self.rbtn_ellipse.setText(_translate("Dialog", "第2个点往后满足椭圆约束"))
        self.rbtn_correspond.setText(_translate("Dialog", "与3D关键点一致"))
        self.groupBox_4.setTitle(_translate("Dialog", "超参数:"))
        self.groupbox_hperparams_adam.setTitle(_translate("Dialog", "Adam"))
        self.label_niters_adam.setText(_translate("Dialog", "迭代次数:"))
        self.label_alpha_adam.setText(_translate("Dialog", "初始学习率:"))
        self.label_beta1_adam.setText(_translate("Dialog", "衰减参数1:"))
        self.label_beta2_adam.setText(_translate("Dialog", "衰减参数2:"))
        self.groupbox_hperparams_lm.setTitle(_translate("Dialog", "Levenberg Marquardt(LM)"))
        self.label_niters_lm.setText(_translate("Dialog", "迭代次数:"))
        self.label_alpha_lm.setText(_translate("Dialog", "初始学习率:"))
        self.label_7.setText(_translate("Dialog", "TBD"))
        self.label_8.setText(_translate("Dialog", "TBD"))
        self.groupbox_hperparams_pso.setTitle(_translate("Dialog", "Particle Swarm Optimization(PSO):"))
        self.label_c1_pso.setText(_translate("Dialog", "学习因子1:"))
        self.label_niters_pso.setText(_translate("Dialog", "迭代次数:"))
        self.label_npops_pso.setText(_translate("Dialog", "粒子数量:"))
        self.label_w_pso.setText(_translate("Dialog", "惯性因子:"))
        self.label_c2_pso.setText(_translate("Dialog", "学习因子2:"))
        self.groupBox_8.setTitle(_translate("Dialog", "优化器:"))
        self.rbtn_adam.setText(_translate("Dialog", "Adam"))
        self.rbtn_lm.setText(_translate("Dialog", "LM"))

